services:
  - type: web
    name: myhomeledger
    env: java
    plan: free
    buildCommand: ./gradlew clean build -x test
    startCommand: java -jar build/libs/app-0.0.1-SNAPSHOT.jar
    autoDeploy: true
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ACCESS_MINUTES
        value: "15"
      - key: JWT_REFRESH_DAYS
        value: "7"
      - key: JPA_DDL_AUTO
        value: update
